<a href="https://colab.research.google.com/github/RezendeRafaelSC/DiabetesPerceptron/blob/main/TerceiraQuestaoAtv9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Treinamento

### Carregando Arquivo de Treinamento (.csv)

In [3]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/ValdirMS/IA---Exerc-cio---08---Rede-Neural-Artificial---Python/main/GarageBand.csv'
base_Treinamento = pd.read_csv(url,sep=';', encoding = 'latin1').values
print("---------------------------------")
print("Dados da Garage Band")
print("---------------------------------")
print(base_Treinamento)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Treinamento[:, 0:6])

print("----------------------------")
print("Classificação Supervisionada")
print("----------------------------")
print(base_Treinamento[:, 7])

---------------------------------
Dados da Garage Band
---------------------------------
[[  6   1   1   1   1   2   1  41]
 [  4   1   0   0   1   5   1  46]
 [  3   0   1   0   0   3   1  30]
 [  2   1   1   1   1   4   1   7]
 [  1   0   0   1   1   1   1   1]
 [  5   0   1   0   0   8   1 100]
 [  3   1   0   1   1   2   0  11]
 [  7   1   0   0   1   3   0  10]
 [  2   1   1   0   1   4   1  15]
 [  6   0   0   0   0   8   1  23]
 [  4   1   1   1   1   9   0  80]
 [  3   0   1   0   0   4   0   5]
 [  1   1   0   1   0   7   1  70]
 [  5   1   1   0   1   3   1  32]
 [  2   0   0   1   0  10   0  12]
 [  7   0   1   1   1   9   1  50]
 [  4   1   1   1   0   5   1  69]
 [  6   0   1   1   0   1   1  37]
 [  3   0   0   0   0  10   1  60]
 [  1   0   1   0   1   6   0  25]
 [  5   1   1   1   0   7   1  95]
 [  2   0   0   0   1   2   0   8]
 [  4   0   0   1   0   3   1  20]
 [  7   0   1   0   0   4   0  14]
 [  6   1   1   0   1   1   0   9]
 [  3   1   0   1   1   8   1  75]
 

### Pré-processamento de Dados

In [4]:
import numpy as np
from sklearn import preprocessing

# Binarizador de rótulo
lb = preprocessing.LabelBinarizer()

data = np.array(base_Treinamento)
entrada = data[:, :-1]
popularidade = data[:, -1]

#Concatenação de Atributos (Colunas)
print("--------------------------------")
print("Atributos de Entrada - Entrada")
print("--------------------------------")
print(entrada)
print("----------------------------------------")
print("Classificação Supervisionada - Popularidade")
print("----------------------------------------")
print(popularidade)

--------------------------------
Atributos de Entrada - Entrada
--------------------------------
[[ 6  1  1  1  1  2  1]
 [ 4  1  0  0  1  5  1]
 [ 3  0  1  0  0  3  1]
 [ 2  1  1  1  1  4  1]
 [ 1  0  0  1  1  1  1]
 [ 5  0  1  0  0  8  1]
 [ 3  1  0  1  1  2  0]
 [ 7  1  0  0  1  3  0]
 [ 2  1  1  0  1  4  1]
 [ 6  0  0  0  0  8  1]
 [ 4  1  1  1  1  9  0]
 [ 3  0  1  0  0  4  0]
 [ 1  1  0  1  0  7  1]
 [ 5  1  1  0  1  3  1]
 [ 2  0  0  1  0 10  0]
 [ 7  0  1  1  1  9  1]
 [ 4  1  1  1  0  5  1]
 [ 6  0  1  1  0  1  1]
 [ 3  0  0  0  0 10  1]
 [ 1  0  1  0  1  6  0]
 [ 5  1  1  1  0  7  1]
 [ 2  0  0  0  1  2  0]
 [ 4  0  0  1  0  3  1]
 [ 7  0  1  0  0  4  0]
 [ 6  1  1  0  1  1  0]
 [ 3  1  0  1  1  8  1]
 [ 5  0  1  0  0  6  1]
 [ 1  1  1  1  1 10  0]
 [ 4  1  0  0  0  7  0]
 [ 2  0  0  0  0  9  1]
 [ 7  1  0  1  1  2  0]
 [ 3  0  1  0  0  8  0]
 [ 6  1  1  0  1  5  0]
 [ 5  0  0  0  0  7  0]
 [ 1  0  0  1  1 10  1]
 [ 4  1  1  0  1  3  0]
 [ 2  1  1  0  0  1  1]
 [ 3  0  0  0  

### Treinamento do Neurônio Perceptron

In [5]:
from sklearn.linear_model import Perceptron
# Treinamento do Perceptron a partir dos atributos de entrada e classificações
modelo = Perceptron()
modelo.fit(entrada, popularidade)

# Acurácia do modelo, que é : 1 - (predições erradas / total de predições)
# Acurácia do modelo: indica uma performance geral do modelo.
# Dentre todas as classificações, quantas o modelo classificou corretamente;
# (VP+VN)/N
print('Acurácia: %.3f' % modelo.score(entrada, popularidade))

Acurácia: 0.300


### ----------------------------------------------------------------------------

# Validação do Aprendizado

### Predição Simples

In [ ]:
RoubouMeuCaminhao = [[3,0,0,1,1,10,0]]
print("Matanza", modelo.predict(RoubouMeuCaminhao))


Matanza [35]


### Predição a partir de base de dados (.csv)

In [6]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/ValdirMS/IA---Exerc-cio---08---Rede-Neural-Artificial---Python/main/GarageBand.csv'
base_Testes = pd.read_csv(url,sep=';', encoding = 'latin1').values
print("----------------------------")
print("Dados da banda - TESTES")
print("----------------------------")
print(base_Testes)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Testes[:, 0:6])

----------------------------
Dados da banda - TESTES
----------------------------
[[  6   1   1   1   1   2   1  41]
 [  4   1   0   0   1   5   1  46]
 [  3   0   1   0   0   3   1  30]
 [  2   1   1   1   1   4   1   7]
 [  1   0   0   1   1   1   1   1]
 [  5   0   1   0   0   8   1 100]
 [  3   1   0   1   1   2   0  11]
 [  7   1   0   0   1   3   0  10]
 [  2   1   1   0   1   4   1  15]
 [  6   0   0   0   0   8   1  23]
 [  4   1   1   1   1   9   0  80]
 [  3   0   1   0   0   4   0   5]
 [  1   1   0   1   0   7   1  70]
 [  5   1   1   0   1   3   1  32]
 [  2   0   0   1   0  10   0  12]
 [  7   0   1   1   1   9   1  50]
 [  4   1   1   1   0   5   1  69]
 [  6   0   1   1   0   1   1  37]
 [  3   0   0   0   0  10   1  60]
 [  1   0   1   0   1   6   0  25]
 [  5   1   1   1   0   7   1  95]
 [  2   0   0   0   1   2   0   8]
 [  4   0   0   1   0   3   1  20]
 [  7   0   1   0   0   4   0  14]
 [  6   1   1   0   1   1   0   9]
 [  3   1   0   1   1   8   1  75]
 [  5   

### Pré-processamento de Dados

In [7]:
import numpy as np
from sklearn import preprocessing

# Binarizador de rótulo
lb = preprocessing.LabelBinarizer()

#Converter todos os atributos menos o outcome(ultima linha) em um array numPy
data = np.array(base_Testes)

entrada = data[:, :-1]
popularidade = data[:, -1]



print("--------------------------------")
print("Atributos de Entrada")
print("--------------------------------")
print(entrada)


--------------------------------
Atributos de Entrada
--------------------------------
[[ 6  1  1  1  1  2  1]
 [ 4  1  0  0  1  5  1]
 [ 3  0  1  0  0  3  1]
 [ 2  1  1  1  1  4  1]
 [ 1  0  0  1  1  1  1]
 [ 5  0  1  0  0  8  1]
 [ 3  1  0  1  1  2  0]
 [ 7  1  0  0  1  3  0]
 [ 2  1  1  0  1  4  1]
 [ 6  0  0  0  0  8  1]
 [ 4  1  1  1  1  9  0]
 [ 3  0  1  0  0  4  0]
 [ 1  1  0  1  0  7  1]
 [ 5  1  1  0  1  3  1]
 [ 2  0  0  1  0 10  0]
 [ 7  0  1  1  1  9  1]
 [ 4  1  1  1  0  5  1]
 [ 6  0  1  1  0  1  1]
 [ 3  0  0  0  0 10  1]
 [ 1  0  1  0  1  6  0]
 [ 5  1  1  1  0  7  1]
 [ 2  0  0  0  1  2  0]
 [ 4  0  0  1  0  3  1]
 [ 7  0  1  0  0  4  0]
 [ 6  1  1  0  1  1  0]
 [ 3  1  0  1  1  8  1]
 [ 5  0  1  0  0  6  1]
 [ 1  1  1  1  1 10  0]
 [ 4  1  0  0  0  7  0]
 [ 2  0  0  0  0  9  1]
 [ 7  1  0  1  1  2  0]
 [ 3  0  1  0  0  8  0]
 [ 6  1  1  0  1  5  0]
 [ 5  0  0  0  0  7  0]
 [ 1  0  0  1  1 10  1]
 [ 4  1  1  0  1  3  0]
 [ 2  1  1  0  0  1  1]
 [ 3  0  0  0  0  2  0]
 

### Predição da Base

In [8]:
base_Predicao = modelo.predict((entrada))
print("Classificações: ", base_Predicao)

Classificações:  [ 9 15  5 15  1  5 11  9 15  2  5  5 70 15 35  2  2 37  2 35  2  8  2  5
  9 99  5 35  2 35 13  5  5  2 88 16 15  2  5  2 21 39  1  2  2  2  9  2
  2  5]


### Retorno aos valores Categóricos

In [9]:
import numpy as np
from sklearn import preprocessing

# Binarizador de rótulo
lb = preprocessing.LabelBinarizer()

#A saída da transformação é também conhecido como codificação 1-de-n
#Transforma valores categóricos equidistantes em valores binários equidistantes.
#Atributos categóricos com valores sim e não
lb.fit(['sim', 'não'])
febre = lb.inverse_transform(atributos_norm[:,0])
enjoo = lb.inverse_transform(atributos_norm[:,1])
dores = lb.inverse_transform(atributos_norm[:,3])

#Atributos categóricos com valores pequenas e grandes
lb.fit(['grandes', 'pequenas'])
manchas = lb.inverse_transform(atributos_norm[:,2])

#Atributos categóricos com valores saudável e doente
lb.fit(['saudável', 'doente'])
predicao = lb.inverse_transform(base_Predicao)

#Concatenação de Atributos (Colunas)
atributos_cat = np.column_stack((base_Testes[:,0],febre,enjoo,manchas,dores,predicao))
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_cat)


NameError: ignored